### ISSUE TITLE
Modify the `abac_api` to fetch data from MongoDB

### ISSUE THREAD

**Issue by shohamyamin** [nadavgross/trino-opa-example#3]
[content_world_attributes.json](https://github.com/nadavgross/trino-opa-example/files/13906741/content_world_attributes.json)
[table_attributes.json](https://github.com/nadavgross/trino-opa-example/files/13906743/table_attributes.json)
TODO:
@nadavgross enter the example files
[user_attributes.json](https://github.com/nadavgross/trino-opa-example/files/13906744/user_attributes.json)

**Comment by nadavgross** [comment]
Changed the issue description with the example files
